### ISSUE TITLE
Juego::mapEntidades

### ISSUE THREAD

**Issue by MartinCura** [PabloFederico/Taller-2015#1]
No entiendo la utilidad de mapEntidades de la clase Juego.
- Primero que nada, un map funciona por pares (key;value), por lo que si la key es TipoEntidad, solo podríamos tener, p.ej., ¡_un_ castillo! Lo único que se me ocurre es que sea una forma rara de Singleton para el manejo de imágenes, y espero que no mucho más. (Extra: ¿por qué pasarle el TipoEntidad al crear la Entidad? No miré todas las clases todavía, pero me pareció raro.)
- Por otro lado, me parece que la coincidencia de nombre entre **Juego::mapEntidades** y **Escenario::mapEntidades** es escapable: habría que por lo menos cambiarle el nombre a alguna de las variables...

Más que nada eso. El código está muy legible por ahora. Mañana sigo poniéndome al día cuando pueda. Saludos!

**Comment by emanuelcondo** [comment]
Juego::mapEntidades
Con respecto a esto, es eso mismo q planteas sobre singleton, es mas que nada por el tema de cargar imagenes, ahora cuando carguemos las entidades al escenario vos podes tener mas de un castillo (por ejemplo), pero cada castillo cuando lo dibujemos va a ser la misma imagen, no tendria sentido que cargue una y otra vez la misma imagen. 

Entidad
Esto es muy general, por ejemplo arbol, agua, tierra los supuse como una entidad, pero Castillo y Soldado como derivados de Entidad, por eso al crear cualquier entidad le debería pasar el tipo (lo vuelvo a decir, es muy generico, se podría mejorar)
Al crear un castillo por ejemplo, Castillo *castle = new Castillo(CASTILLO); como que queda medio trucho no?, habría que hacer algun tipo de cambio.
En vez de un map creo que se podría hacer con un vector de entidades (pensandolo mejor).

Escenario::mapEntidades
Claro, debería llamarse algo como mapPosicionesEntidades

Cualquier mejora es bienvenida.

**Comment by MartinCura** [comment]
Ahora me gusta más, con el nuevo nombre. Igual después voy a trabajar más la abstracción y modularidad, separando un poco más en distintas clases.

Sí, lo de entidades se ve medio medio. Si no te molesta después lo altero un poco jaja.
